// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptTraceScope } from "./PromptTraceScope";
import type { PromptTraceSection } from "./PromptTraceSection";

export type PromptTraceResponseEvent = { scope: PromptTraceScope, sections: Array<PromptTraceSection>, };
